[package]
name = "gremlin"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
feed-rs = "2.3.1"
log = "0.4.27"
reqwest = "0.12.15"
tokio = { version = "1", features = ["full"] }
